---
kind: pipeline
type: kubernetes
name: runner-hello

steps:
- name: hello
  image: alpine
  pull: if-not-exists
  commands:
    - echo "hello from k8s drone"
    - uname -a
    - echo "KEY=123" > .env.sh
- name: finish
  image: alpine
  commands:
    - source .env.sh
    - echo "finish"
    - echo $KEY

trigger:
  event:
    - push

---
kind: pipeline
type: kubernetes
name: go-hello

steps:
- name: test
  image: golang
  pull: if-not-exists
  volumes:
  - name: deps
    path: /go
  commands:
    - cd ./go/
    - echo "---- go test"
    - go test
    - ls -l /go
    - du -h -d1 /go
    - date >> /go/date.txt

- name: build
  image: golang
  pull: if-not-exists
  volumes:
  - name: deps
    path: /go
  commands:
    - cd ./go/
    - echo "---- go build"
    - go build
    - cat /go/date.txt
    - du -h -d1 /go
    - ls -l go*

- name: make
  image: golang
  pull: if-not-exists
  commands:
    - cd ./go/
    - make
    - ls -l hello*

volumes:
- name: deps
  temp: {}

---
kind: pipeline
type: kubernetes
name: go-hello-vcache

steps:
- name: build
  image: golang
  pull: if-not-exists
  volumes:
  - name: go-cache
    path: /go
  commands:
    - "[ -f /go/last-modify.txt ] && tail -1 /go/last-modify.txt"
    - date >> /go/last-modify.txt
    - cd ./go/
    - echo "---- go build"
    - make
    - ls -l hello*
    - mkdir -p ../dist/

- name: upx
  image: cnbattle/drone-upx
  settings:
    save_file: ./dist/hello
    original_file: ./go/hello
  when:
    event: tag

- name: release
  image: plugins/gitea-release
  settings:
    base_url: "https://git.yq16.fun/"
    api_key:
      from_secret: drone-fx-token
    #files: "./go/hello*"
    files: "./dist/hello*"
    title: "New Release"
    note: "note here"
    prerelease: true
    checksum:
      - md5
  when:
    event: tag

- name: docker-image
  image: banzaicloud/drone-kaniko
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: harbor-test-bot-name
    password:
      from_secret: harbor-test-bot-pass
    registry: harbor.yq16.fun
    repo: test/gitest
    tags:
      - latest
      - ${DRONE_TAG}
  when:
    event: tag

volumes:
- name: go-cache
  claim:
    name: drone-go-cache-pvc
